info:
    name: service-negationscope
    version: 0.0.0
    description: Negation Scope Service
    documentation: https://github.com/sutd-statnlp/service-negationscope

logging:
    level:
        ROOT: DEBUG
        org.statnlp.services: DEBUG

spring:
    application:
        name: service-negationscope
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

server:
    port: 8000

management:
    security:
        enabled: false

async:
    executor:
        core-pool-size: 4
        queue-capacity: 600
        thread-prefix: StatNLP-

