server:
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

logging:
    level:
        ROOT: INFO
        org.statnlp.services: INFO

spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
